# Generated by Django 5.1 on 2024-08-08 07:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0003_journey_crew_alter_journey_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="departure_time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2024, 8, 8, 7, 5, 3, 109837)
                    )
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("cargo", "journey", "seat")},
        ),
    ]
