# Generated by Django 5.1 on 2024-08-09 13:55

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0005_alter_journey_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="departure_time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2024, 8, 9, 13, 55, 3, 118811)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="train_station.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
