# Generated by Django 5.1 on 2024-08-10 08:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "train_station",
            "0006_alter_journey_departure_time_alter_ticket_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="departure_time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2024, 8, 10, 8, 48, 48, 859889, tzinfo=datetime.timezone.utc
                        )
                    )
                ]
            ),
        ),
    ]
