# Generated by Django 5.1 on 2024-08-11 08:19

import datetime
import django.core.validators
import train_station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0008_alter_journey_departure_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.train_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="departure_time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2024, 8, 11, 8, 19, 20, 646344, tzinfo=datetime.timezone.utc
                        )
                    )
                ]
            ),
        ),
    ]
